const types = {
  GET_ARTICLES: 'GET_ARTICLES',
  GET_ARTICLE: 'GET_ARTICLE',
  ADD_ARTICLE: 'ADD_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
};
export default types;
